# Generated by Django 3.2.25 on 2024-05-23 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=255)),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('community_name', models.CharField(max_length=255)),
                ('community_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('directory_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('directory_name', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('directory_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.directory')),
                ('related_community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.community')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('media_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=255)),
                ('media_link', models.CharField(max_length=255)),
                ('author_link', models.CharField(default=None, max_length=255, null=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('user_action_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=255)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.action')),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.community')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('role_request_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('community_id', models.UUIDField()),
                ('is_responded', models.BooleanField(default=False)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.role')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('rel_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('community_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.community')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bio', models.TextField(blank=True, max_length=500)),
                ('is_author', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('media_link_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('grade_val', models.FloatField(default=0)),
                ('admin_grade_val', models.FloatField(default=0)),
                ('grade_count', models.IntegerField(default=0)),
                ('admin_grade_count', models.IntegerField(default=0)),
                ('directory_parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.directory')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.media')),
                ('related_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.community')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('grade_value', models.FloatField()),
                ('media_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.medialink')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorRequest',
            fields=[
                ('author_request_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=255)),
                ('is_responded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
