# Generated by Django 3.2.25 on 2024-05-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.UUIDField(primary_key=True, serialize=False)),
                ('community_name', models.CharField(max_length=255)),
                ('community_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.UUIDField(primary_key=True, serialize=False)),
                ('media_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=255)),
                ('media_link', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('author_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.UUIDField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_bio', models.TextField()),
                ('is_author', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('role_request_id', models.UUIDField(primary_key=True, serialize=False)),
                ('community_id', models.UUIDField()),
                ('is_responded', models.BooleanField(default=False)),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.role')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.user')),
            ],
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('media_link_id', models.UUIDField(primary_key=True, serialize=False)),
                ('media_link_name', models.CharField(max_length=255)),
                ('directory_parent', models.UUIDField()),
                ('related_community', models.UUIDField()),
                ('grade', models.IntegerField()),
                ('media_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.media')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.user'),
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('directory_id', models.UUIDField(primary_key=True, serialize=False)),
                ('directory_name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(null=True)),
                ('directory_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.directory')),
                ('related_community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.community')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorRequest',
            fields=[
                ('author_request_id', models.UUIDField(primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=255)),
                ('is_responded', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.user')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.UUIDField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=255)),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.role')),
            ],
        ),
    ]
